### ISSUE TITLE
Redirect when logged-in

### ISSUE THREAD

**Issue by tejasmanohar** [iheanyi/facebook-page-unliker#2]
http://pageunliker.com/ should redirect to http://pageunliker.com/likes when user is logged-in

**Comment by iheanyi** [comment]
Can you post your console output please? If there are any errors, that is.

**Comment by tejasmanohar** [comment]
http://i.imgur.com/mr8Y9sl.png

**Comment by iheanyi** [comment]
Fixed.

**Comment by tejasmanohar** [comment]
lol thanks man
